version: ~> 1.0
dist: bionic
language: go
os: linux
jobs:
  include:
    - go: "1.14.x"
    - go: "1.14.x"
      osx_image: "xcode11.3"
      os: osx
    - go: "1.13.x"
    - go: "1.12.x"
      env:
        GO111MODULE="on"

install:
  - go get github.com/tchajed/goose/cmd/goose
  - go get ./...
script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet ./...
  - go test -v ./...
  - make goose-output

notifications:
  email: false
